### ISSUE TITLE
pysigma needs update

### ISSUE THREAD

**Issue by marcurdy** [7RedViolin/pySigma-backend-carbonblack#7]
pyproject.toml lists pysigma 0.9.6. sigma-cli uses the latest 0.10.5 and refuses to install your plugin.

**Comment by marcurdy** [comment]
I want to use this plugin with sigma-cli for conversions of rules.
"sigma plugins install" needs >=0.10.x to install your plugin, but it fails the compatibility check and throws python errors if I ignore checks.

I'm requesting an uplift to 0.10.3 or higher.

**Comment by 7RedViolin** [comment]
Hey @marcurdy ! Thanks for the heads up - I pushed out v0.1.5 which should fix the issue. From my testing, it appears the only change needed was the pyproject.toml as the code still worked as expected. However, if this didn't fix the errors you are seeing, definitely let me know!

**Comment by marcurdy** [comment]
It will be good. I already tested prior but dropping it into my Python lib
folder.
Thanks
