### ISSUE TITLE
Removal of leading wildcard

### ISSUE THREAD

**Issue by Sam0x90** [7RedViolin/pySigma-backend-carbonblack#9]
Hello guys,

Not sure if https://sigconverter.io/ is running the latest backend, but I do believe we should change the pipeline by removing the leading wildcards (the ending one as well if not mistaken). This would improve query performance. 
Here is the reference from the vendor's documentation: https://docs.vmware.com/en/VMware-Carbon-Black-EDR/7.8.0/vmw-cb-edr-ug/GUID-0B27FED5-3C9D-440A-A30A-16FA8570C9DA.html

Hope that helps.
Cheers!

**Comment by 7RedViolin** [comment]
Hi @Sam0x90 ! Appreciate the bug report! This should be fixed in v0.1.6 but let me know if the issue still persists

**Comment by Sam0x90** [comment]
Awesome, thanks
